package org.example;

/**
 * Provides simple method to demonstrate use of the new enhanced error message
 * generated by {@code NullPointerException}.
 */
public final class Calculator {
  // Hide the constructor as it is not needed for this class.
  private Calculator() {
  }

  /**
   * Ridiculously simple method to accept three inputs for demonstrating use
   * of the new enhanced error message generated by
   * {@code NullPointerException}.
   *
   * @param a a {@code long} value
   * @param b another {@code long} value
   * @param c a third {@code long} value
   * @return the product of the three provided parameter values
   */
  public static long compute(final long a, final long b, final long c) {
    return a * b * c;
  }
}
